# Copyright (c) 2025 ZitaoTech
# SPDX-License-Identifier: MIT

description: Sensor Gear Behavior (mgear/sgear)

compatible: "zmk,behavior-sensor-gear"


properties:
  "#binding-cells":
    type: int
    required: true
    const: 1
  label:
    type: string
    required: true
