# Copyright (c) 2025 ZitaoTech
# SPDX-License-Identifier: MIT

description: Sensor Gear Behavior (mgear/sgear)

compatible: "zmk,behavior-sensor-gear"

include: ["one-cell.yaml"]

properties:
  label:
    type: string
    required: true
